### ISSUE TITLE
Nsis error - Invalid command: ,

### ISSUE THREAD

**Issue by sergioatzori** [evshiron/nwjs-builder-phoenix#115]
Hi,
Trying to build my app in Windows 10 I get this error:
Building nsis target starts...
Processing config: C:\Users\XXXXXXXXXX\STAFF-nw\node_modules\nwjs-builder-phoenix\assets\nsis\nsisconf.nsh
Processing script file: "C:\Users\XXXXXX~1\AppData\Local\Temp\tmp-4872LI4tH8y6ahfN" (UTF8)
Invalid command: ,
Error in script "C:\Users\XXXXXX~1\AppData\Local\Temp\tmp-4872LI4tH8y6ahfN" on line 20 -- aborting creation process
Error: ERROR_EXIT_CODE code = 1
    at ChildProcess.<anonymous> (C:\Users\XXXXXXXXXX\STAFF-nw\node_modules\nwjs-builder-phoenix\src\lib\nsis-gen\index.ts:35:31)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)

Here's my package.json:
{
  "name": "XXXXXXXXXX_BackStage_SANDBOX",
  "version": "0.9.5",
  "main": "index.html",
  "appUrl": "http://XXXXXXXXXX/",
  "appTitle": "XXXXXXXXXX - SANDBOX",
  "description": "XXXXXXXXXX - Backoffice WebApp - SANDBOX",
  "author": "XXXXXXXXXX <XXXXXXXXXX@gmail.com>",
  "webkit": {
    "page-cache": false
  },
  "keywords": [
    "truccheria",
    "backoffice",
    "staff",
    "ordini",
    "sito",
    "utenti"
  ],
  "window": {
    "title": "XXXXXXXXXX BackStage",
    "icon": "staff-app.png",
    "width": 1280,
    "height": 920,
    "position": "center"
  },
  "devDependencies": {
    "nwjs-builder-phoenix": "^1.14.*",
    "typescript": "^2.2.1"
  },
  "build": {
    "nwVersion": "0.30.3",
    "packed": true,
    "appId": "XXXXXXXXXX.sandbox-backstage",
    "targets": [
      "nsis"
    ],
    "excludes": [
      "./nwjs*"
    ],
    "strippedProperties": [
      "build"
    ],
    "outputPattern": "${NAME} ${VERSION} ${PLATFORM} ${ARCH}",
    "win": {
      "productName": "XXXXXXXXXXBackStage",
      "companyName": "XXXXXXXXXX SRL",
      "copyright": "2018 - XXXXXXXXXX SRL",
      "icon": "./staff-app.ico",
      "unIcon": "./staff-app_uninst.ico"
    },
    "nsis": {
      "installDirectory": "$PROGRAMFILES\\${_COMPANYNAME}\\${_APPNAME}",
      "languages": [
        "Italian",
        "English"
      ],
      "diffUpdaters": true
    }
  },
  "scripts": {
    "dist": "build --tasks win-x64,linux-x64 --mirror https://dl.nwjs.io/ .",
    "start": "run --x64 --mirror https://dl.nwjs.io/ ."
  },
  "webview": {
    "partitions": [
      {
        "name": "trusted",
        "accessible_resources": [
          "<all_urls>"
        ]
      }
    ]
  }
}

Here's the temp script generated:
################################################################################
#
# Generated by nsis-gen.
#
################################################################################

################################################################################
#
# Strings
#
################################################################################

!define _APPNAME "LaTruccheria BackStage"
!define _COMPANYNAME "LaTruccheria SRL"
!define _DESCRIPTION "LaTruccheria BackStage - Backoffice WebApp - SANDBOX"
!define _VERSION "0.9.5.0"
!define _COPYRIGHT "2018 - LaTruccheria SRL"
!define _OUTPUT "C:\Users\LaTruccheria\STAFF-nw\dist\La_Truccheria_BackStage_SANDBOX 0.9.5 win x64-Setup.exe"

,
LangString CREATE_DESKTOP_SHORTCUT 1033 "Create Desktop Shortcut"
LangString INSTALLING 1033 "Installing"
        

################################################################################
#
# General
#
################################################################################

Unicode true

Name "${_APPNAME}"
Caption "${_APPNAME}"
BrandingText "${_APPNAME} ${_VERSION}"

SetCompressor /SOLID lzma
OutFile "${_OUTPUT}"

InstallDir "$PROGRAMFILES\${_COMPANYNAME}\${_APPNAME}"
InstallDirRegKey HKCU "Software\${_APPNAME}" "InstallDir"

RequestExecutionLevel user
XPStyle on

################################################################################
#
# Modern UI
#
################################################################################

!include "MUI2.nsh"

Function CreateDesktopShortcut
    CreateShortcut "$DESKTOP\${_APPNAME}.lnk" "$INSTDIR\${_APPNAME}.exe"
FunctionEnd

!define MUI_STARTMENUPAGE_REGISTRY_ROOT "HKCU"
!define MUI_STARTMENUPAGE_REGISTRY_KEY "Software\${_APPNAME}"
!define MUI_STARTMENUPAGE_REGISTRY_VALUENAME "StartMenuFolder"

!define MUI_FINISHPAGE_SHOWREADME ""
!define MUI_FINISHPAGE_SHOWREADME_TEXT "$(CREATE_DESKTOP_SHORTCUT)"
!define MUI_FINISHPAGE_SHOWREADME_FUNCTION CreateDesktopShortcut

Var StartMenuFolder

!define MUI_FINISHPAGE_RUN "$INSTDIR\${_APPNAME}.exe"

!insertmacro MUI_PAGE_WELCOME
!insertmacro MUI_PAGE_DIRECTORY
!insertmacro MUI_PAGE_STARTMENU "Application" $StartMenuFolder
!insertmacro MUI_PAGE_INSTFILES
!insertmacro MUI_PAGE_FINISH

!insertmacro MUI_UNPAGE_WELCOME
!insertmacro MUI_UNPAGE_CONFIRM
!insertmacro MUI_UNPAGE_INSTFILES
!insertmacro MUI_UNPAGE_FINISH

!insertmacro MUI_LANGUAGE "Italian"
!insertmacro MUI_LANGUAGE "English"

!insertmacro MUI_RESERVEFILE_LANGDLL

################################################################################
#
# Versioning
#
################################################################################

VIProductVersion "${_VERSION}"
VIAddVersionKey /LANG=0 "ProductName" "${_APPNAME}"
VIAddVersionKey /LANG=0 "CompanyName" "${_COMPANYNAME}"
VIAddVersionKey /LANG=0 "FileDescription" "${_DESCRIPTION}"
VIAddVersionKey /LANG=0 "FileVersion" "${_VERSION}"
VIAddVersionKey /LANG=0 "LegalCopyright" "${_COPYRIGHT}"

################################################################################
#
# Hooks
#
################################################################################

Function .onInit

    !insertmacro MUI_LANGDLL_DISPLAY

FunctionEnd

################################################################################
#
# Install
#
################################################################################

Section -Install

SetShellVarContext current
SetOverwrite ifnewer

WriteRegStr HKCU "Software\${_APPNAME}" "InstallDir" "$INSTDIR"

SetOutPath "$INSTDIR"
FILE /r .\*.*

!insertmacro MUI_STARTMENU_WRITE_BEGIN "Application"

    CreateDirectory "$SMPROGRAMS\$StartMenuFolder"
    CreateShortcut "$SMPROGRAMS\$StartMenuFolder\${_APPNAME}.lnk" "$INSTDIR\${_APPNAME}.exe"
    CreateShortcut "$SMPROGRAMS\$StartMenuFolder\Uninstall.lnk" "$INSTDIR\Uninstall.exe"

!insertmacro MUI_STARTMENU_WRITE_END

  WriteUninstaller "$INSTDIR\Uninstall.exe"

SectionEnd

################################################################################
#
# Uninstall
#
################################################################################

Section Uninstall

# FIXME: Remove installed files only.
RMDir /r "$INSTDIR"

!insertmacro MUI_STARTMENU_GETFOLDER "Application" $StartMenuFolder

Delete "$SMPROGRAMS\$StartMenuFolder\${_APPNAME}.lnk"
Delete "$SMPROGRAMS\$StartMenuFolder\Uninstall.lnk"
RMDir "$SMPROGRAMS\$StartMenuFolder"

Delete "$DESKTOP\${_APPNAME}.lnk"

DeleteRegKey HKCU "Software\${_APPNAME}"

SectionEnd

Sorry for the long post, I cannot find a better way to format code! :-(

Thank you

**Comment by sangyoo91** [comment]
How did anyone fix this?

**Comment by ark76r** [comment]
The error occurs when more than one language is selected for the installer. Probably the Nsis configuration generator cannot handle this case properly.
