### ISSUE TITLE
Windows Build From macOS - problems with wine install

### ISSUE THREAD

**Issue by SteveBrooker** [evshiron/nwjs-builder-phoenix#121]
I have been using nw-builder-phoenix for a couple of years with no problems, however my trusty 17" macBookPro finally died and I have to buy a new laptop and reinstall node, npm and wine.
nw-builder-phoenix now rebuilds the mac version of my nw.js app however when run it kicks off a wine updater which uses lots of cpu and does nothing however long I leave it running it (hours!).

Reading on the internet I discovered that this is a problem with the brew install of wine and that the problem did not exist with the package from wineHQ.  So I uninstalled wine using brew (very easy) and installed the package from wineHQ (no sure it is going to be so easy to uninstall this one!)

However nw-builder-phoenix now crashes with the following error
{ Error: spawn wine ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:229:19)
    at onErrorNT (internal/child_process.js:406:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn wine',
  path: 'wine',
  spawnargs:
   [  ---text here has been removed---  ] }
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! TeamMap@0.62.155 win: `build --win --x64 .`
npm ERR! Exit status 255

All help very gratefully received

**Comment by conceptualspace** [comment]
obvious question but you're running nw-builder from the wine console, right?

**Comment by SteveBrooker** [comment]
No. 

I am running it through npm from the mac console with either 
"npm run win" or "npm run both” executing the following package.json

“npm run prod" and  "npm run mac” both work fine, as the other two previously did up to about 3 months ago when I had to reinstall wine.

{
  "name": "TeamMap",
  "version": "0.62.160",
  "description": "teammap",
  "license": "INTBOX Solutions Ltd",
  "author": {
    "name": "Steve Brooker",
    "url" : "www.teammap.net"
   },
  "main": "index.min.html",
  "window": {
    "min_width": 800,
    "min_height": 600,
    "icon": "TeamMap-Chrome-128-128.png"
  },
  "build": {
    "nwVersion": "lts",
    "targets": ["zip","nsis7z"],
    "strippedProperties": ["scripts","devDependencies","build"],
    "win": { "versionStrings": {"ProductName":"TeamMap",
    							"CompanyName":"INTBOX Solutions Ltd",
    							"LegalCopyright":"© IntBox Solutions Ltd 2018"},
    		 "icon":"app.ico" },
    "mac": { "copyright":"© IntBox Solutions Ltd 2018",
             "icon":"app.icns" },
    "nsis": {
      "diffUpdaters": true
    }
  },
  "scripts": {
    "dev": "nw .",
    "prod": "build --mac --x64 .",
    "mac": "build --mac --x64 .",
    "win": "build --win --x64 .",
    "both": "build --mac --win --x64 ."
  },
  "devDependencies": {
    "nw": "^0.21.6",
    "nwjs-builder-phoenix": "^1.9.3"
  }
}

**Comment by conceptualspace** [comment]
nwbuilder isnt able to find wine for whatever reason so try it from wine console (should be in applications), bet that works

**Comment by NickClark** [comment]
Ya, I had to add it to my path and reload the terminal.
