### ISSUE TITLE
nwVersion "stable" unsupported on Mac

### ISSUE THREAD

**Issue by peter23** [evshiron/nwjs-builder-phoenix#139]
This line https://github.com/evshiron/nwjs-builder-phoenix/blob/e9c26b61669589e599da95ee82ac3bb489c6dd04/src/lib/Builder.ts#L397 crashes build process for Mac when nwVersion is "stable".

```
TypeError: Invalid Version: stable
    at new SemVer (/somewhere/node_modules/semver/semver.js:312:11)
    at compare (/somewhere/node_modules/semver/semver.js:585:10)
    at Function.lt (/somewhere/node_modules/semver/semver.js:619:10)
    at Builder.canRenameMacHelperApp (/somewhere/node_modules/nwjs-builder-phoenix/src/lib/Builder.ts:397:18)
    at Builder.<anonymous> (/somewhere/node_modules/nwjs-builder-phoenix/src/lib/Builder.ts:294:19)
    at step (/somewhere/node_modules/nwjs-builder-phoenix/dist/lib/Builder.js:40:23)
    at Object.next (/somewhere/node_modules/nwjs-builder-phoenix/dist/lib/Builder.js:21:53)
    at /somewhere/node_modules/nwjs-builder-phoenix/dist/lib/Builder.js:15:71
    at __awaiter (/somewhere/node_modules/nwjs-builder-phoenix/dist/lib/Builder.js:11:12)
    at Builder.updateHelperPlist (/somewhere/node_modules/nwjs-builder-phoenix/dist/lib/Builder.js:286:16)
    at Builder.<anonymous> (/somewhere/node_modules/nwjs-builder-phoenix/src/lib/Builder.ts:448:20)
    at step (/somewhere/node_modules/nwjs-builder-phoenix/dist/lib/Builder.js:40:23)
    at Object.next (/somewhere/node_modules/nwjs-builder-phoenix/dist/lib/Builder.js:21:53)
    at /somewhere/node_modules/nwjs-builder-phoenix/dist/lib/Builder.js:15:71
    at __awaiter (/somewhere/node_modules/nwjs-builder-phoenix/dist/lib/Builder.js:11:12)
    at Builder.prepareMacBuild (/somewhere/node_modules/nwjs-builder-phoenix/dist/lib/Builder.js:500:16)
    at Builder.<anonymous> (/somewhere/node_modules/nwjs-builder-phoenix/src/lib/Builder.ts:669:24)
    at step (/somewhere/node_modules/nwjs-builder-phoenix/dist/lib/Builder.js:40:23)
    at Object.next (/somewhere/node_modules/nwjs-builder-phoenix/dist/lib/Builder.js:21:53)
    at fulfilled (/somewhere/node_modules/nwjs-builder-phoenix/dist/lib/Builder.js:12:58)
```

**Comment by kriefsacha** [comment]
Found a solution @peter23 ?

**Comment by peter23** [comment]
> Found a solution @peter23 ?

No.
I just set exact version number.
