### ISSUE TITLE
Build Windows version under macOS 10.15 fails.

### ISSUE THREAD

**Issue by cry0m1** [evshiron/nwjs-builder-phoenix#151]
Hi, used ```nwjs-sdk-v0.41.2-osx-x64.zip```
and after update to new Catalina macOS (Note: now it supports only 64bit apps)
win builds are broken (no App.exe file after build):

```
Starting building tasks... { tasks: [ [ 'win', 'x64' ] ], concurrent: true }
Building for win, x64 starts...
Error: spawn wine ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn wine',
  path: 'wine',
  spawnargs: [
    '/Users/user/_my_backup/my_dev/js/node_modules/rcedit/bin/rcedit.exe',
    '/Users/user/_my_backup/my_dev/MyAppNameRelease/MyAppName-0.10.14-31-win-x64/nw.exe',
    '--set-version-string',
    'ProductName',
    'MyAppName',
    '--set-version-string',
    'CompanyName',
    'MyAppName',
    '--set-version-string',
    'FileDescription',
    undefined,
    '--set-version-string',
    'LegalCopyright',
    '',
    '--set-file-version',
    '0.10.14-31',
    '--set-product-version',
    '0.10.14-31',
    '--set-icon',
    '/Users/picture.ico'
  ]
}
Building for win, x64 ends within 1.10s.
```
Maybe it tries to spawn 32bit wine? If Yes - it will not work, I tried to install wine from brew - it shows an error with CPU architecture.

**Comment by cry0m1** [comment]
Seems to me because of rcedit https://github.com/evshiron/nwjs-builder-phoenix/blob/526564786479740b9013356dceeee90fffec7734/src/lib/Builder.ts#L256 .

calls for 

```
 if (process.platform !== 'win32') {
    args.unshift(rcedit)
    rcedit = 'wine'
    // Supress fixme: stderr log messages
    spawnOptions.env.WINEDEBUG = '-all'
  }
```

Also I tried to download different x64 versions of https://github.com/electron/rcedit/releases rcedit - does not help.

**Comment by evshiron** [comment]
Greetings,

I haven't used NW.js for years, and I don't have the passion to maintain this project anymore. Sorry for the inconvenience.

To answer your question, `Error: spawn wine ENOENT` indicates that `wine` might not be installed, or it's an x86 executable (mine is, which is installed via Homebrew) and Catalina refuses to run it.

I haven't upgraded to Catalina and that's the information I can provide. By the way, `wine64` might never work on macOS, [read this](https://www.winehq.org/wwn/364#Wine64%20on%20Mac%20OS%20X).

**Comment by cry0m1** [comment]
Hi @evshiron, I just tracking this issue here and linked to NWJS repo.
You are right. So if no plans to support, just ignore pls.

**Comment by remi-grumeau** [comment]
Hi @evshiron,
Does "I don't have the passion to maintain this project anymore" means NWJS is soon to be dead?
Which tool would you recommend to us instead of NWjs then ?

Thx

**Comment by undavide** [comment]
@remi-grumeau, I understand that @evshiron is the creator of `nwjs-builder-phoenix`, the builder tool for `nw.js`: that has a different creator (@rogerwang) and is still maintained as far as I know. Or were you asking which builder tool to use?
