### ISSUE TITLE
Building on macOS failed

### ISSUE THREAD

**Issue by oyed** [evshiron/nwjs-builder-phoenix#56]
When running `build --mac --x64 --mirror https://dl.nwjs.io/ .`, I'm getting the following output:

```
> imperiumforge@0.1.0 dist /Users/tom/Sites/ImperiumForge/Client
> build --mac --x64 --mirror https://dl.nwjs.io/ .

Starting building tasks... { tasks: [ [ 'mac', 'x64' ] ], concurrent: false }
Building for mac, x64 starts...
Fetching NW.js binary... { platform: 'mac', arch: 'x64', version: 'lts', flavor: 'normal' }
TypeError: callback is not a function
    at /Users/tom/Sites/ImperiumForge/Client/node_modules/fs-extra/node_modules/jsonfile/index.js:46:5
    at /Users/tom/Sites/ImperiumForge/Client/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:503:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! imperiumforge@0.1.0 dist: `build --mac --x64 --mirror https://dl.nwjs.io/ .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the imperiumforge@0.1.0 dist script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/tom/.npm/_logs/2017-06-24T11_44_30_500Z-debug.log
```

**Comment by oyed** [comment]
My build config:

```
{
    "build": {
        "appId": "com.imperiumforge",
        "nwVersion": "0.23.4",
        "packed": true,
        "targets": [
            "zip"
        ],
        "win": {
            "productName": "ImperiumForge",
            "companyName": "OYED",
            "copyright": "Copyright (C) OYED"
        },
        "mac": {
            "name": "imperiumforge",
            "plistStrings": {
                "CFBundleIdentifier": "com.imperiumforge"
            },
            "displayName": "ImperuimForge",
            "copyright": "Copyright (C) OYED"
        }
    }
}
```

**Comment by oyed** [comment]
I notice it's pulling in `lts` for the `version` instead of what I specified (`0.23.4`), might this be the issue?

**Comment by evshiron** [comment]
Although it looks like an issue relating to upstream changes, but I can't reproduce it on a fresh installation of the sample project. Could you try modifying the sample project and see if it builds?

```bash
git clone https://github.com/evshiron/nwjs-builder-phoenix
cd ./nwjs-builder-phoenix/assets/project/
npm install
vi package.json
npm run build
```

If your `0.23.4` wasn't used, make sure the directory given to `nwjs-builder-phoenix` contains the right `package.json` just in case.

**Comment by oyed** [comment]
After changing the demo to not use a mirror (It seems the mirror you have in there doesn't have `0.23.4` on there yet), it works just fine.

However my project _does_ have a `package.json` with the above `build` config in it and just isn't getting read... I have no idea why.

**Comment by oyed** [comment]
Scripts being used:

```
"scripts": {
        "dev": "cross-env NODE_ENV=development webpack --progress --hide-modules",
        "watch": "cross-env NODE_ENV=development webpack --watch --progress --hide-modules",
        "prod": "cross-env NODE_ENV=production webpack --progress --hide-modules",
        "build": "build --mac --x64 .",
        "start": "run --x64 ."
    },
```

I'm starting `nwjs-builder-phoenix` in the directory the `package.json` is in.

**Comment by oyed** [comment]
It seems removing `node_modules` and rerunning `npm install` has fixed the issue. Not sure why but eh.
