### ISSUE TITLE
buffer-equal module not found

### ISSUE THREAD

**Issue by RichardFoss** [evshiron/nwjs-builder-phoenix#62]
I have built an x64 Setup file using the sdk nwFlavor. Within the index.html, I had the following require:

  var bufferEqual = require('buffer-equal');

The buffer-equal module is one of the modules in my node-modules folder. I get the following error message in the developer tools console:

Uncaught Error: Cannot find module 'buffer-equal'
    at Function.Module._resolveFilename (module.js:509:15)

Any idea what this might be caused by? Other modules such as fs, xml2js and mac-address are OK.

When I ran the setup file, it did not install in the given program files folder, and when I selected the shortcut I was redirected to the .exe in my \dist folder. A possible factor (?).

I did also request an x86 build, but that didn't work for the following given reason:

Building directory target starts...
Error: rcedit.exe failed with exit code 1. Fatal error: Unable to commit changes
    at ChildProcess.<anonymous> (D:\AVBFlexSDKDistr\node_modules\rcedit\lib\rcedit.js:60:16)

Any help much appreciated.

**Comment by evshiron** [comment]
Emmm. Is this `buffer-equal` listed in your `dependencies`?

Do you have any anti-virus softwares? If so, please disable it temporarily and see if `rcedit` works.

A reproducible sample will be appreciated.

**Comment by RichardFoss** [comment]
Thanks for your continued assistance evshiron! Thanks for correctly pointing out the dependency issue. I needed to add 2 dependencies:

  "dependencies": {
    "buffer-equal": "^1.0.0",
    "debug": "^2.6.8"
  }

With this in place, the built myPgm.exe in the \dist\myPgm-1.0.0-win-x64  runs. This is a big step forward! Something that confuses me - I use many modules, why would these particular two need to be listed, and not the others?

I do still have three issues:

1. The rcedit.exe issue for the x86 build persists when I turn off real time virus scanning. To provide you with a sample, what would I need to do?

2. My nsis install directory is given as:
      "installDirectory": "$PROGRAMFILES\\${_COMPANYNAME}\\${_APPNAME}"
It resolves to c:\Program Files (x86)\...... However, it doesn't write to that location. I have to provide a folder such as c:\myPgm to perform the installation. I do have administrator rights. This may well be my own system issue.

3. If I want to have an xml file incorporated into the install folder, would I use the 'files' build option?

Thanks again for all the help.

**Comment by evshiron** [comment]
When you install dependencies via `npm install`, you should use `--save` or `--save-dev` to save them to the `package.json`. This is how node.js works.
`nwjs-builder-phoenix` will only copy production dependencies (via `npm install --save`) when building, if a module isn't required for production, it's not copied for smaller bundle size.

* This issue was reported before but I couldn't reproduce it on neither macOS via `wine` nor Windows 10. Maybe the executable is being used at that time, incorrect permission has been configured, or anti-virus softwares are protecting the executable from modifying.
* I don't know. I will test it later.
* By default, files and directories at the project root will be copied (excluding the output directory), and the directory structure will be preserved. Use `build.files` and `build.excludes` to modify the default behavior (see [Options](https://github.com/evshiron/nwjs-builder-phoenix/blob/master/docs/Options.md)).

**Comment by RichardFoss** [comment]
Thanks for another comprehensive answer evshiron!

I understand the dependency issue - thanks!

Points 1 and 2: I will test on another machine and report back.

Point 3:  I have an xml file at the project root that is not copied. I see that .png and .ico files are also not copied. Is there a way to get the xml file copied? I see from the build files option that the default is '**/*' and from this I assumed that it should be copied.
