### ISSUE TITLE
ETIMEDOUT

### ISSUE THREAD

**Issue by sharifzadesina** [evshiron/nwjs-builder-phoenix#78]
Hi, thank you for the package.

When I run both `run` and `build` commands I get this error:

```
{ Error: connect ETIMEDOUT 34.205.42.151:443
    at Object._errnoException (util.js:1041:11)
    at _exceptionWithHostPort (util.js:1064:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1153:14)
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '34.205.42.151',
  port: 443 }
```

Everything was OK, I didn't change anything but now this error happens.

**Comment by sharifzadesina** [comment]
This was cause of my connection, closed.
