### ISSUE TITLE
Windows 8.1 building error: EPERM - syscall 'spawn' in nsis-gen

### ISSUE THREAD

**Issue by codekiln** [evshiron/nwjs-builder-phoenix#85]
I'm attempting to compile the example project with an `npm link`'d version of `nw-builder-phoenix` in Windows 8.1. When I compile, I get a permissions error when `nsis-gen` attempts to spawn `makensis.exe`. 

1. I downloaded `nw-builder-phoenix` to `C:\Users\dev\nw-builder-phoenix` and then ran `npm install` there as well as `npm link`. 
2. I copied `nw-builder-phoenix/assets/project` to `C:\Users\dev\nwtest`. I ran `npm link nw-builder-phoenix` to ensure it was using the local version I needed. I also ran `npm install`. I can confirm that the `node_modules` has a junction created for `nw-builder-phoenix`.
3. I modified sample application's package.json to bring it up to date and adapt it to Windows:

```
{
  "name": "project",
  "version": "0.1.0",
  "description": "description",
  "main": "index.html",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "build": "cross-env DEBUG=* build --tasks win-x64 ."
  },
  "author": "evshiron",
  "license": "MIT",
  "build": {
    "appId": "io.github.evshiron.nwjs-builder-phoenix.project",
    "nwVersion": "0.25.2",
    "packed": false,
    "targets": [
      "nsis7z"
    ],
    "strippedProperties": [
      "build"
    ],
    "outputPattern": "${NAME}-${VERSION}-${PLATFORM}-${ARCH}",
    "win": {
      "productName": "Project",
      "companyName": "nwjs-builder-phoenix",
      "copyright": "copyright",
      "icon": "./assets/pd.ico"
    },
    "nsis": {
      "diffUpdaters": true
    }
  },
  "devDependencies": {
    "cross-env": "^5.0.5",
    "nwjs-builder-phoenix": "1.14.6",
    "typescript": "^2.2.1"
  },
  "window": {
    "icon": "./assets/pd.png"
  }
}
```

When I run `npm run build`, I get: 
```
  build:nsisBuild build args are C:\Users\dev\nwjs-builder-phoenix\assets\nsis\makensis.exe,/NOCD,/INPUTCHARSET,UTF8,C:\Users\dev\AppData\Local\Temp\tmp-2596wIhETQ3vt3XN +0ms
{ Error: spawn EPERM
    at exports._errnoException (util.js:1022:11)
    at ChildProcess.spawn (internal/child_process.js:317:11)
    at Object.exports.spawn (child_process.js:491:9)
    at Object.<anonymous> (C:\Users\dev\nwjs-builder-phoenix\src\lib\nsis-gen\index.ts:28:19)
    at step (C:\Users\dev\nwjs-builder-phoenix\dist\lib\nsis-gen\index.js:32:23)
    at Object.next (C:\Users\dev\nwjs-builder-phoenix\dist\lib\nsis-gen\index.js:13:53)
    at C:\Users\dev\nwjs-builder-phoenix\dist\lib\nsis-gen\index.js:7:71
    at Promise (<anonymous>)
    at __awaiter (C:\Users\dev\nwjs-builder-phoenix\dist\lib\nsis-gen\index.js:3:12)
    at Object.nsisBuild (C:\Users\dev\nwjs-builder-phoenix\dist\lib\nsis-gen\index.js:53:12)
    at Builder.<anonymous> (C:\Users\dev\nwjs-builder-phoenix\src\lib\Builder.ts:729:15)
    at step (C:\Users\dev\nwjs-builder-phoenix\dist\lib\Builder.js:40:23)
    at Object.next (C:\Users\dev\nwjs-builder-phoenix\dist\lib\Builder.js:21:53)
    at fulfilled (C:\Users\dev\nwjs-builder-phoenix\dist\lib\Builder.js:12:58)
    at <anonymous> code: 'EPERM', errno: 'EPERM', syscall: 'spawn' }
```

Here you can see that I've added a debug message in `nw-builder-phoenix/src/lib/nsis-gen/index.ts` to echo out the build args: `C:\Users\dev\nwjs-builder-phoenix\assets\nsis\makensis.exe,/NOCD,/INPUTCHARSET,UTF8,C:\Users\dev\AppData\Local\Temp\tmp-2596wIhETQ3vt3XN`. 

If I run this directly in the command prompt (normal user), I get `Access is denied`:
```
C:\Users\dev\nwtest>C:\Users\dev\nwjs-builder-phoenix\assets\nsis\makensis.exe /NOCD /INPUTCHARSET UTF8 C:\Users\dev\AppData\
Local\Temp\tmp-2596wIhETQ3vt3XN
Access is denied.
```

If I run the project *without* the link step (using the downloaded npm package of `nw-builder-phoenix`), I don't run into this error. My question is, how do you get around this when you're developing `nw-builder-phoenix`? 

My aim is to get access to the generated nsis script so I can modify it before it is called.

**Comment by codekiln** [comment]
I think I figured this out - I used git in cygwin to clone the repo, but I used the regular windows console to execute the `npm link` and `npm build`. I think think checking out the executable in the context of cygwin messed up the executable, perhaps because there's no .gitattributes marking the .exe as a binary file.

Key lesson: if you are hacking on `nwjs-builder-phoenix` locally, `git clone nwjs-builder-phoenix` must be done from the normal windows cli.
